version: '3.7'

services:
  db:
    container_name: kitodo-presentation-db
    image: mariadb:10
    environment:
      - MARIADB_DATABASE=typo3-dfgviewer-v5-ocr
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
      - MARIADB_USER=$MARIADB_USER
      - MARIADB_PASSWORD=$MARIADB_PASSWORD
    #volumes:
    #  - ./volumes/database:/var/lib/mysql
    restart: unless-stopped
  main:
    build: .
    image: kitodo/dfgviewer:5.3-ocr-221101
    container_name: kitodo-presentation-main
    ports:
      - "0.0.0.0:$PORT:80"
    environment:
      - DB_ADDR=db
      - DB_PORT=3306
      - DB_NAME=typo3-dfgviewer-v5-ocr
      - DB_USER=$MARIADB_USER
      - DB_PASSWORD=$MARIADB_PASSWORD
      - TYPO3_ADMIN_USER=$TYPO3_ADMIN_USER
      - TYPO3_ADMIN_PASSWORD=$TYPO3_ADMIN_PASSWORD
      - TYPO3_ADDITIONAL_CONFIGURATION=$TYPO3_ADDITIONAL_CONFIGURATION
      - HOST=$FullyQualifiedDomainName
    volumes:
      - ./volumes/fileadmin:/var/www/typo3/public/fileadmin/
    depends_on:
      - db
      - solr
    restart: unless-stopped
  solr:
    container_name: kitodo-presentation-solr
    image: solr:8
    user: root:root
    command: bash -c "find '/opt/solr/bin/' -maxdepth 1 -type f -name '*' -exec ln -v -s -f {} '/usr/games/' ';' \; 
              find '/opt/docker-solr/scripts' -maxdepth 1 -type f -name '*' -exec ln -v -s -f {} '/usr/games/' ';' \; 
              find '/opt/java/openjdk/bin' -maxdepth 1 -type f -name '*' -exec ln -v -s -f {} '/usr/games/' ';' \; 
              ls -l /usr/games/ 
              && apt-get install lsof 
              && cp -av /data/solrconfig/dlf /opt/solr/server/solr/configsets/ 
              && chown -R solr /opt/solr/server/solr/configsets
              && mkdir -p /opt/solr/contrib/ocrsearch/lib 
              && cd  /opt/solr/contrib/ocrsearch/lib/ 
              && wget https://github.com/dbmdz/solr-ocrhighlighting/releases/download/wip/solr-ocrhighlighting-0.8.4-SNAPSHOT.jar 
              && chown -R solr .
              && su -c 'solr-create -c presentation' solr"

#TODO: find a better solution for broken $PATH ("su -c 'echo $PATH' solr/root" not the same as "echo $PATH" from rsp. users -> not finding the solr paths -> find and /usr/games workaround)
#some commands worth keeping for the moment
    # command: 
              # && cd /opt/docker-solr/scripts/
              # && su -c 'echo $$PATH' solr"
              # && su -c 'PATH=$$PATH:/opt/docker-solr/scripts && solr-create -c presentation' solr"
    # command: solr-create -c presentation
    # command: solr-precreate my_core /data/solrconfig/dlf

    volumes:
      - ./volumes/solr/solrconfig:/data/solrconfig/
      - ./volumes/solr/solrsetup.sh:/data/solrsetup.sh
      # - ./volumes/solr/solrdata:/var/solr
    ports:
      - "0.0.0.0:8983:8983"
    restart: unless-stopped
